@startuml
'https://plantuml.com/use-case-diagram

class mainAplication {
--
+start
}
class menuPrincipalController{
-listaDeFicheros
--
# onBotonNuevoClick
# onBotonCargarPartidaClick
# onBotonVolverMenuClick
# onBotonCargarFicheroClick
- getNombreFicheros
+ initialize
}
class menuPrincipalvista{}
class simuladorDeVida{}
class menuConfiguracionController{
--
#updateGUIWithModel
#initializeSpinners
-añadirFiltroSpinner
#onBotonGuardarClick
-continuarJuego
-empezarNuevoJuego
#onBotonReiniciarClick
#onBotonVolverClick
+initialize
-initializeControllers
}
class menuConfiguracionInicioVista{}
class menuConfiguracionPausaVista{}
class tableroController{
- juegoActual: simuladorDeVida
--
# onBotonPausaClick
# onBotonReanudarClick
# onBotonPasarTurnoClick
-avanzarJuego
# onBotonConfiguracionClick
#onBotonCerrarClick
#onBotonPantallaCompletaClick
#onBotonMinimizarClick
#onBotonMenuPrincipalClick
-volverAlMenuPrincipal
#onBotonGuardarPartidaClick
#onBotonGuardarComoClick
#guardarPartida
#guardarComo
#mostrarElementosCasilla
#crearTablero
-crearGridTablero
#onBotonFinalizarPartidaClick
+finalizarPartida
-crearArbolVista
}
class tableroVista{}
class casillaController{
- casillaActual
--
+añadirIndividuo
-añadirIndividuoAux
+eliminarIndividuo
+añadirRecurso
-añadirRecursoAux
+eliminarRecurso
}
class casillaVista{}
class simuladorDeVida{
-tablero
-bucle
--
+comenzar
}
class tablero{
-casillas
}
class bucleDeControl{
-tablero
-individuos
-recursos
--
+run
-ejecutarBucle
}
class casillaTablero{
-tablero
-individuos
-recursos
--
+addIndividuo
-addIconoIndividuo
+delIndividuo
+addRecurso
-addIconoRecurso
+delRecurso
+resetVisual
}
class individuos{}
class recursos{}
class cargarJuegoVista{}
class elementoCasillaBoxVista{}
menuPrincipalController-->cargarJuegoVista :onBotonCargarPartidaClick
cargarJuegoVista-->menuPrincipalController: onBotonVolverMenuClick
mainAplication--->menuPrincipalController :start
menuPrincipalController-->menuConfiguracionController :onBotonNuevoClick
menuPrincipalController ---> menuPrincipalvista
menuPrincipalvista--->menuPrincipalController
menuConfiguracionInicioVista---> menuConfiguracionController
menuConfiguracionController-->menuConfiguracionInicioVista
menuConfiguracionController-->menuConfiguracionPausaVista
menuConfiguracionPausaVista--->menuConfiguracionController
tableroController--->simuladorDeVida
tableroVista--->tableroController
tableroController-->tableroVista
casillaController-->casillaVista
casillaVista-->casillaController
simuladorDeVida-->tablero
simuladorDeVida-->bucleDeControl
bucleDeControl-->tablero
tablero-->casillaTablero
casillaTablero-->tablero
casillaTablero--->individuos
casillaTablero-->recursos
menuConfiguracionController-->tableroController :onBotonGuardarClick
tableroController-->menuConfiguracionController: onBotonConfiguracionClick
tableroController-->casillaController :mostrarElementosCasilla
casillaController-->tableroController
casillaTablero-->elementoCasillaBoxVista
elementoCasillaBoxVista-->casillaTablero
casillaVista-->elementoCasillaBoxVista
menuPrincipalController--> tableroController : onBotonCargarFicheroClick
menuConfiguracionController-->menuPrincipalController: onBotonVolverClick
tableroController-->menuPrincipalController: #onBotonMenuPrincipalClick
casillaController-->casillaTablero
casillaController-->individuos
casillaController-->recursos
bucleDeControl-->individuos
bucleDeControl-->recursos
tableroController-->finalizarPartidaVista
@enduml